DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;


CREATE TABLE users (
    id INTEGER PRIMARY KEY ,
    "user" TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY ,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY ("author_id") REFERENCES "user" (id)
);